# Generated by Django 5.2.14 on 2026-06-01 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('assignment_published', 'Assignment Published'), ('assignment_due_soon', 'Assignment Due Soon'), ('assignment_submitted', 'Assignment Submitted'), ('low_submission_rate', 'Low Submission Rate'), ('weak_topic_detected', 'Weak Topic Detected'), ('intervention_created', 'Intervention Created'), ('intervention_updated', 'Intervention Updated'), ('intervention_note_added', 'Intervention Note Added'), ('intervention_due', 'Intervention Due'), ('progress_report_available', 'Progress Report Available'), ('learning_recommendation', 'Learning Recommendation'), ('system', 'System')], default='system', max_length=64)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=16)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status', 'created_at'], name='notificatio_recipie_3f77fb_idx'), models.Index(fields=['school', 'notification_type', 'created_at'], name='notificatio_school__4acfa4_idx'), models.Index(fields=['recipient', 'priority', 'created_at'], name='notificatio_recipie_6048c4_idx')],
            },
        ),
    ]
