# Generated by Django 5.2.14 on 2026-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment_published', 'Assignment Published'), ('assignment_due_soon', 'Assignment Due Soon'), ('assignment_deadline_extended', 'Assignment Deadline Extended'), ('assignment_reopened', 'Assignment Reopened'), ('assignment_submitted', 'Assignment Submitted'), ('low_submission_rate', 'Low Submission Rate'), ('weak_topic_detected', 'Weak Topic Detected'), ('intervention_created', 'Intervention Created'), ('intervention_updated', 'Intervention Updated'), ('intervention_note_added', 'Intervention Note Added'), ('intervention_due', 'Intervention Due'), ('progress_report_available', 'Progress Report Available'), ('learning_recommendation', 'Learning Recommendation'), ('system', 'System')], default='system', max_length=64),
        ),
    ]
