# Generated by Django 5.2.14 on 2026-06-01 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('assignments', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic_support', 'Academic Support'), ('parent_contact', 'Parent Contact'), ('remedial_assignment', 'Remedial Assignment'), ('revision_class', 'Revision Class'), ('attendance_followup', 'Attendance Follow-up'), ('behavior_followup', 'Behavior Follow-up'), ('other', 'Other')], default='academic_support', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=16)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('weak_student', 'Weak Student'), ('weak_topic', 'Weak Topic'), ('progress_report', 'Progress Report'), ('remediation_plan', 'Remediation Plan'), ('admin_intervention_dashboard', 'Admin Intervention Dashboard')], default='manual', max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interventions', to='schools.school')),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interventions', to='assignments.assignment')),
                ('source_class_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interventions', to='academics.classarm')),
                ('source_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interventions', to='academics.subject')),
                ('source_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_interventions', to='academics.topic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_notes', to=settings.AUTH_USER_MODEL)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='interventions.studentintervention')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentintervention',
            index=models.Index(fields=['school', 'student', 'status'], name='interventio_school__640337_idx'),
        ),
        migrations.AddIndex(
            model_name='studentintervention',
            index=models.Index(fields=['school', 'status', 'priority'], name='interventio_school__67db58_idx'),
        ),
        migrations.AddIndex(
            model_name='studentintervention',
            index=models.Index(fields=['school', 'due_date'], name='interventio_school__be2d69_idx'),
        ),
    ]
