# Generated by Django 5.2.14 on 2026-06-03 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('auth', 'Auth'), ('academics', 'Academics'), ('question_bank', 'Question Bank'), ('assignment', 'Assignment'), ('submission', 'Submission'), ('intervention', 'Intervention'), ('notification', 'Notification'), ('import', 'Import'), ('user_management', 'User Management'), ('system', 'System')], db_index=True, max_length=32)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=128)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('target_user_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='schools.school')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'category', 'created_at'], name='audit_audit_school__d9b59a_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['target_user', 'created_at'], name='audit_audit_target__514ec6_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
