# Generated by Django 5.2.14 on 2026-05-22 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('question_bank', '0002_question_content_hash_questionimportbatch_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionSuggestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion_type', models.CharField(choices=[('topic_difficulty_explanation', 'Topic, Difficulty, and Explanation'), ('explanation_only', 'Explanation Only'), ('difficulty_only', 'Difficulty Only'), ('duplicate_quality_check', 'Duplicate and Quality Check')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider', models.CharField(default='openai', max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('suggested_difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16, null=True)),
                ('suggested_explanation', models.TextField(blank=True)),
                ('duplicate_warning', models.TextField(blank=True)),
                ('quality_warning', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_suggestion_runs', to='question_bank.question')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_question_suggestion_runs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_question_suggestion_runs', to='schools.school')),
                ('suggested_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_question_suggestion_runs', to='academics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='ai_generati_school__2c5825_idx'), models.Index(fields=['requested_by', 'status'], name='ai_generati_request_0f4ec6_idx'), models.Index(fields=['question', 'suggestion_type'], name='ai_generati_questio_b07844_idx')],
            },
        ),
    ]
