# Generated by Django 5.2.14 on 2026-06-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers')], max_length=32)),
                ('file', models.FileField(upload_to='user_imports/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_import_batches', to='schools.school')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('failed', 'Failed'), ('warning', 'Warning'), ('duplicate', 'Duplicate')], default='pending', max_length=16)),
                ('raw_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('warning_message', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='accounts.userimportbatch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='userimportbatch',
            index=models.Index(fields=['school', 'import_type', 'status'], name='accounts_us_school__3dd682_idx'),
        ),
        migrations.AddIndex(
            model_name='userimportbatch',
            index=models.Index(fields=['uploaded_by', 'status'], name='accounts_us_uploade_309f68_idx'),
        ),
        migrations.AddIndex(
            model_name='userimportrow',
            index=models.Index(fields=['batch', 'status'], name='accounts_us_batch_i_5a6dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='userimportrow',
            index=models.Index(fields=['user'], name='accounts_us_user_id_b6b19c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_user_import_row_number_per_batch'),
        ),
    ]
