# Generated by Django 5.2.14 on 2026-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='deadline_status_at_submit',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_after_due_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
