# Generated by Django 5.2.14 on 2026-05-23 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('question_bank', '0002_question_content_hash_questionimportbatch_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='mixed', max_length=16)),
                ('question_count_requested', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('class_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to='academics.classarm')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to='academics.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to='academics.topic')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('options_snapshot', models.JSONField(blank=True, default=list)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_session_questions', to='question_bank.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='practice.practicesession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_label', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_answers', to='question_bank.questionoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='practice.practicesession')),
                ('session_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='practice.practicesessionquestion')),
            ],
            options={
                'ordering': ['session_question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['school', 'student', 'status'], name='practice_pr_school__4c57bf_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['school', 'subject', 'topic'], name='practice_pr_school__34a8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['student', 'started_at'], name='practice_pr_student_266868_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['session', 'order'], name='practice_pr_session_d9b1db_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['question'], name='practice_pr_questio_07ac4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='practicesessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_practice_question_per_session'),
        ),
        migrations.AddConstraint(
            model_name='practicesessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_practice_question_order_per_session'),
        ),
        migrations.AddIndex(
            model_name='practiceanswer',
            index=models.Index(fields=['session', 'session_question'], name='practice_pr_session_614e95_idx'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.UniqueConstraint(fields=('session', 'session_question'), name='unique_practice_answer_per_session_question'),
        ),
    ]
