# Generated by Django 5.2.14 on 2026-05-19 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('jamb_past_question', 'JAMB Past Question'), ('waec_past_question', 'WAEC Past Question'), ('neco_past_question', 'NECO Past Question'), ('teacher_created', 'Teacher Created'), ('ai_generated', 'AI Generated'), ('school_created', 'School Created')], max_length=32)),
                ('exam_body', models.CharField(blank=True, max_length=32)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', '-year'],
                'constraints': [models.UniqueConstraint(fields=('name', 'source_type', 'year'), name='unique_question_source_name_type_year', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='academics.classlevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='academics.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='academics.topic')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_bank.questionsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.question')),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(fields=('question', 'label'), name='unique_question_option_label'), models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_option_per_question')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['school', 'subject', 'topic', 'class_level'], name='question_ba_school__33ce4a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'is_active'], name='question_ba_status_9a0f22_idx'),
        ),
    ]
