# Generated by Django 5.2.14 on 2026-05-22 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='QuestionImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON')], max_length=16)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_import_batches', to='schools.school')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='question_bank.questionsource')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='question_bank.questionimportbatch')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='question_bank.question')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='questionimportbatch',
            index=models.Index(fields=['school', 'status'], name='question_ba_school__4ab1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='questionimportbatch',
            index=models.Index(fields=['uploaded_by', 'status'], name='question_ba_uploade_b1fcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='questionimportrow',
            index=models.Index(fields=['batch', 'status'], name='question_ba_batch_i_4a68d3_idx'),
        ),
        migrations.AddIndex(
            model_name='questionimportrow',
            index=models.Index(fields=['content_hash'], name='question_ba_content_7001be_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_question_import_row_number_per_batch'),
        ),
    ]
