# Generated by Django 5.2.14 on 2026-05-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_question_content_hash_questionimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='has_diagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image')], default='image', max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_media/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_manual_review', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_media', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='question_bank.question')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['question', 'is_active'], name='question_ba_questio_23db27_idx'), models.Index(fields=['media_type', 'is_active'], name='question_ba_media_t_2fe09d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('question',), name='unique_primary_active_question_media')],
            },
        ),
    ]
