# Generated by Django 5.2.14 on 2026-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_question_diagram_description_question_has_diagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimportbatch',
            name='warning_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionimportrow',
            name='warning_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionimportbatch',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('zip', 'ZIP'), ('xlsx', 'Excel'), ('json', 'JSON')], max_length=16),
        ),
    ]
